force-app/main/default/objects/Pagination_Metadata__mdt/Pagination_Metadata__mdt.object-meta.xml
<CustomObject>
    <label>Pagination Metadata</label>
    <pluralLabel>Pagination Metadatas</pluralLabel>
</CustomObject>

force-app/main/default/objects/Pagination_Metadata__mdt/fields/Amount_Records__c.field-meta.xml
<CustomField>
    <fullName>Amount_Records__c</fullName>
    <label>Amount Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PaginationControllerTest.cls
@isTest
public class PaginationControllerTest {
    @isTest 
    public static void fetchPaginationMetadataTest() {
        List<Pagination_Metadata__mdt> paginationList = [
            SELECT Amount_Records__c, Default__c 
            FROM Pagination_Metadata__mdt
        ];
        List<Decimal> paginationResult = PaginationController.fetchPaginationMetadata().amountRecords;

        System.assertEquals(paginationList.size(), paginationResult.size());
    }
}