force-app/main/default/objects/Pagination_Metadata__mdt/Pagination_Metadata__mdt.object-meta.xml
<CustomObject>
    <label>Pagination Metadata</label>
    <pluralLabel>Pagination Metadatas</pluralLabel>
</CustomObject>

force-app/main/default/objects/Pagination_Metadata__mdt/fields/Amount_Records__c.field-meta.xml
<CustomField>
    <fullName>Amount_Records__c</fullName>
    <label>Amount Records</label>
    <precision>18</precision>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

force-app/main/default/classes/PaginationController.cls
public with sharing class PaginationController {

    @AuraEnabled(cacheable=true)
    public static Pagination fetchPaginationMetadata() {
        List<Pagination_Metadata__mdt> paginationList = [
            SELECT Amount_Records__c, Default__c 
            FROM Pagination_Metadata__mdt
            WITH SECURITY_ENFORCED 
            ORDER BY Amount_Records__c
        ];

        Decimal defaultAmount = 0;
        List<Decimal> amountRecordList = new List<Decimal>();
        for (Pagination_Metadata__mdt pm : paginationList) {
            amountRecordList.add(pm.Amount_Records__c);
            if (pm.Default__c) {
                defaultAmount = pm.Amount_Records__c;
            }
        }

        Pagination pagination = new Pagination();
        pagination.amountRecords = amountRecordList;
        pagination.defaultAmountRecord = defaultAmount;
        return pagination;
    }

    public class Pagination {
        @AuraEnabled
        public List<Decimal> amountRecords {get; set;}

        @AuraEnabled
        public Decimal defaultAmountRecord {get; set;}
    }
}