force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Medical Healthcare</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Expense Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ExpenseController.cls
public with sharing class ExpenseController {

    public static String getFilterParameter(String search) {
        String filter = '';
        if (String.isNotBlank(search)) {
            filter = 'WHERE Name LIKE \'%' + String.escapeSingleQuotes(search) + '%\' ' + 
                     'OR Category__c LIKE \'%' + String.escapeSingleQuotes(search) + '%\' ' + 
                     'OR Label__c LIKE \'%' + String.escapeSingleQuotes(search) + '%\' ';
        }
        return filter;
    }

    public static Integer amountExpenses(String search) {
        String filter = getFilterParameter(search);
        String queryString = 'SELECT COUNT() ' + 
                             'FROM Expense__c ' + 
                             filter +
                             'WITH SECURITY_ENFORCED ';
        return Database.countQuery(queryString);
    }
    
    @AuraEnabled(Cacheable=true)
    public static Expenses getExpenses(String search, Integer tableOffset, Integer tableSize) {
        String filter = getFilterParameter(search);
        String queryString = 'SELECT Id, Name, Amount__c, Category__c, Expense_Date__c, Label__c ' +
                             'FROM Expense__c ' + 
                             filter +
                             'WITH SECURITY_ENFORCED ' +
                             'LIMIT :tableSize ' +
                             'OFFSET :tableOffset ';
        List<Expense__c> expenseList = database.query(queryString);
        Expenses expense = new Expenses();
        expense.expenseRecord = expenseList;
        expense.amountRecord = amountExpenses(search);
        return expense;
    }

    public class Expenses {
        @AuraEnabled
        public List<Expense__c> expenseRecord {get; set;}

        @AuraEnabled
        public Integer amountRecord {get; set;}
    }
}