force-app/main/default/objects/Expense__c/Expense__c.object-meta.xml
<CustomObject>
    <label>Expense</label>
    <nameField>
        <displayFormat>EX-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Expenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Expense__c/fields/Amount__c.field-meta.xml
<CustomField>
    <fullName>Amount__c</fullName>
    <label>Amount</label>
    <precision>7</precision>
    <scale>2</scale>
    <type>Currency</type>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Category__c.field-meta.xml
<CustomField>
    <fullName>Category__c</fullName>
    <label>Category</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Housing</fullName>
            </value>
            <value>
                <fullName>Transportation</fullName>
            </value>
            <value>
                <fullName>Food</fullName>
            </value>
            <value>
                <fullName>Medical Healthcare</fullName>
            </value>
            <value>
                <fullName>Others</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/objects/Expense__c/fields/Expense_Date__c.field-meta.xml
<CustomField>
    <fullName>Expense_Date__c</fullName>
    <defaultValue>Today()</defaultValue>
    <label>Expense Date</label>
    <required>true</required>
    <type>Date</type>
</CustomField>

force-app/main/default/classes/ExpenseControllerTest.cls
@isTest
public class ExpenseControllerTest {

    @testSetup
    public static void setupData() {
        Expense__c expenseOne = new Expense__c();
        expenseOne.Amount__c = 123;
        expenseOne.Category__c = 'Housing';
        expenseOne.Expense_Date__c = Date.today();
        expenseOne.Label__c = 'Test1';
        insert expenseOne;

        Expense__c expenseTwo = new Expense__c();
        expenseTwo.Amount__c = 30;
        expenseTwo.Category__c = 'Housing';
        expenseTwo.Expense_Date__c = Date.today();
        expenseTwo.Label__c = 'Test2';
        insert expenseTwo;

        Expense__c expenseThree = new Expense__c();
        expenseThree.Amount__c = 345;
        expenseThree.Category__c = 'Transportation';
        expenseThree.Expense_Date__c = Date.today();
        expenseThree.Label__c = 'Car';
        insert expenseThree;
    }

    @isTest 
    public static void getExpensesTest() {
        Test.startTest();
        List<Expense__c> expenseResult = ExpenseController.getExpenses('Test', 0, 10).expenseRecord;
        Integer amountResult = ExpenseController.getExpenses('Car', 1, 10).amountRecord;
        System.assertEquals(2, expenseResult.size());
        System.assertEquals(1, amountResult);
        Test.stopTest();  
    }
}